# Generated by AICR dev — do not edit.
#
# One AICR component. localformat emits up to four folders for it — pre,
# primary, post, readiness — and they chain here in that order. A slot exists
# only when the bundle emitted that folder, so depends_on across a missing slot
# is a no-op rather than a hole in the chain.
#
# The recipe's edges sit on the module CALL in ../../main.tf, not on a resource
# in here: a depends_on on the call is a fact about everything the component
# expands into.
#
# Every slot's description carries a content digest, because helm_release sees a
# local chart's PATH, version and values but never its rendered manifests —
# editing a template in a bundled folder otherwise produces no plan diff at all.
# The digest makes that content an ordinary in-place upgrade. A slot installing
# an upstream chart has none: repository and version already name its content.

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

# Containment shim. A release's state describes objects inside one cluster; if
# that cluster is replaced they are gone and the state is a lie. Triggering on
# the endpoint ties every release here to the cluster's lifetime.
resource "null_resource" "cluster" {
  triggers = {
    endpoint = var.cluster_endpoint
  }
}

# Pre-manifests: prerequisites the chart's own pods need, such as a Namespace
# carrying PSS labels.
resource "helm_release" "pre" {
  count = var.pre_chart == null ? 0 : 1

  name             = "${var.release_name}-pre"
  namespace        = var.namespace
  create_namespace = var.create_namespace

  description = var.pre_digest == null ? null : "aicr content ${var.pre_digest}"

  chart = var.pre_chart

  wait          = var.wait
  wait_for_jobs = var.wait
  timeout       = var.timeout
  atomic        = var.atomic

  lifecycle {
    create_before_destroy = true
    replace_triggered_by  = [null_resource.cluster]
  }
}

# The component's own chart.
resource "helm_release" "this" {
  name      = var.release_name
  namespace = var.namespace

  # The head slot owns the namespace. If pre ran it exists already, and Helm 3
  # refuses to adopt a namespace another release created out-of-band.
  create_namespace = var.pre_chart == null ? var.create_namespace : false

  description = var.chart_digest == null ? null : "aicr content ${var.chart_digest}"

  chart      = var.chart
  repository = var.repository
  version    = var.chart_version

  values = [for f in var.values_files : file(f)]

  # wait turns an ordering edge into a readiness edge. It does NOT wait on
  # custom-resource status: a component whose real signal is a CR condition
  # needs its readiness gate. See README.md.
  wait          = var.wait
  wait_for_jobs = var.wait
  timeout       = var.timeout
  atomic        = var.atomic

  # Escape hatch, off by default like the provider's own. A chart referencing
  # CRDs that a PRIOR release installs can fail dry-run validation; this is the
  # blunt fix, narrowing wait and ordering is the better one.
  disable_openapi_validation = var.disable_openapi_validation

  depends_on = [helm_release.pre]

  lifecycle {
    create_before_destroy = true
    replace_triggered_by  = [null_resource.cluster]
  }
}

# Post-manifests: raw YAML instantiating CRDs the chart above installs, so it
# applies once those are registered.
resource "helm_release" "post" {
  count = var.post_chart == null ? 0 : 1

  name      = "${var.release_name}-post"
  namespace = var.namespace

  description = var.post_digest == null ? null : "aicr content ${var.post_digest}"

  chart = var.post_chart

  wait          = var.wait
  wait_for_jobs = var.wait
  timeout       = var.timeout
  atomic        = var.atomic

  disable_openapi_validation = var.disable_openapi_validation

  depends_on = [helm_release.this]

  lifecycle {
    create_before_destroy = true
    replace_triggered_by  = [null_resource.cluster]
  }
}

# Readiness gate: a Job asserting the signal that actually means ready, such as
# a CR condition helm cannot see.
resource "helm_release" "readiness" {
  count = var.readiness_chart == null ? 0 : 1

  name      = "${var.release_name}-readiness"
  namespace = var.namespace

  # An assertion is only true of the thing it was made about, so the gate has to
  # re-run when either half moves: its own content, and the component it is
  # about. metadata.revision increments on every upgrade of that component and
  # at no other time, so a re-apply with nothing changed produces no diff here.
  #
  # Both signals ride in description, which is an ordinary updatable attribute.
  # That matters: the Job inside is re-run by the helm hook on upgrade, so the
  # release never has to be REPLACED — and replacement is what this slot cannot
  # survive, since it inherits create_before_destroy from its siblings under
  # --terraform-cluster-rollover and two releases sharing a name in one cluster
  # collide.
  description = "aicr gate content=${var.readiness_digest} component-rev=${helm_release.this.metadata.revision}"

  chart = var.readiness_chart

  # Hardcoded, not var.wait: the waiting IS the gate. An async component may
  # skip waiting on its own workloads, never on the gate that asserts it came
  # up.
  #
  # What blocks on the gate is HELM, not these flags: the Job is a
  # post-install,post-upgrade hook, and helm runs a Job hook to completion
  # before the release reports success, failing the release if it fails. A hook
  # is not a release resource, so wait_for_jobs never sees it; wait is here for
  # the ServiceAccount, RBAC and ConfigMap the chart does install. No atomic —
  # a rollback would delete the Job and its logs, which are the diagnosis.
  wait          = true
  wait_for_jobs = true
  timeout       = var.timeout

  depends_on = [helm_release.this, helm_release.post]

  # Same containment as every other slot: a completed gate describes objects in
  # one cluster, and a replaced cluster makes that assertion false.
  lifecycle {
    create_before_destroy = true
    replace_triggered_by  = [null_resource.cluster]
  }
}
