# Generated by AICR dev — do not edit.

variable "release_name" {
  description = "Helm release name."
  type        = string
}

variable "namespace" {
  description = "Namespace to install into."
  type        = string
}

variable "create_namespace" {
  description = "Create the namespace if it does not exist."
  type        = bool
  default     = true
}

variable "chart" {
  description = "Chart name for an upstream repository, or a path to a chart directory in this bundle."
  type        = string
}

variable "repository" {
  description = "Chart repository URL (https:// or oci://). Null for a chart directory in this bundle."
  type        = string
  default     = null
}

variable "chart_version" {
  description = "Upstream chart version. Null for a chart directory in this bundle."
  type        = string
  default     = null
}

variable "values_files" {
  description = "Values files to layer, in order."
  type        = list(string)
  default     = []
}

variable "wait" {
  description = "Wait for the release's workloads to become ready."
  type        = bool
  default     = true
}

variable "timeout" {
  description = "Wait timeout, in seconds."
  type        = number
  default     = 900
}

variable "atomic" {
  description = "Roll the release back if it fails to install."
  type        = bool
  default     = false
}

variable "disable_openapi_validation" {
  description = "Skip OpenAPI validation of rendered manifests against the live cluster."
  type        = bool
  default     = false
}

variable "cluster_endpoint" {
  description = "Cluster API endpoint. Replacing the cluster changes this, which replaces the release."
  type        = string
  default     = ""
}
