# Generated by x-tfgen from an AICR recipe. Do not edit by hand.
#
# One module call per AICR component, with depends_on carrying the recipe's
# DependencyRefs verbatim. The recipe's precomputed deploymentOrder is
# deliberately NOT consumed: it is a linearisation of this graph, and handing a
# linearisation to an engine that schedules graphs is lossy.

resource "kind_cluster" "dc" {
  name           = "${var.cluster_name}-${var.generation}"
  node_image     = var.node_image
  wait_for_ready = true
}

module "agentgateway_crds" {
  source = "./modules/component"

  release_name  = "agentgateway-crds"
  namespace     = "agentgateway-system"
  chart         = "oci://cr.agentgateway.dev/charts/agentgateway-crds"
  chart_version = "v1.5.0"
  values_file   = "${path.module}/bundle/001-agentgateway-crds/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint
}

module "agentgateway_crds_post" {
  source = "./modules/component"

  release_name = "agentgateway-crds-post"
  namespace    = "agentgateway-system"
  chart        = "${path.module}/bundle/002-agentgateway-crds-post"
  values_file  = "${path.module}/bundle/002-agentgateway-crds-post/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.agentgateway_crds]
}

module "cert_manager" {
  source = "./modules/component"

  release_name  = "cert-manager"
  namespace     = "cert-manager"
  chart         = "cert-manager"
  repository    = "https://charts.jetstack.io"
  chart_version = "v1.20.2"
  values_file   = "${path.module}/bundle/003-cert-manager/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint
}

module "agentgateway" {
  source = "./modules/component"

  release_name  = "agentgateway"
  namespace     = "agentgateway-system"
  chart         = "oci://cr.agentgateway.dev/charts/agentgateway"
  chart_version = "v1.5.0"
  values_file   = "${path.module}/bundle/004-agentgateway/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.agentgateway_crds_post, module.cert_manager]
}

module "agentgateway_post" {
  source = "./modules/component"

  release_name = "agentgateway-post"
  namespace    = "agentgateway-system"
  chart        = "${path.module}/bundle/005-agentgateway-post"
  values_file  = "${path.module}/bundle/005-agentgateway-post/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.agentgateway]
}

module "nfd" {
  source = "./modules/component"

  release_name  = "nfd"
  namespace     = "node-feature-discovery"
  chart         = "node-feature-discovery"
  repository    = "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chart_version = "0.19.0"
  values_file   = "${path.module}/bundle/006-nfd/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint
}

module "network_operator" {
  source = "./modules/component"

  release_name  = "network-operator"
  namespace     = "nvidia-network-operator"
  chart         = "network-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "26.4.1"
  values_file   = "${path.module}/bundle/007-network-operator/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.cert_manager, module.nfd]
}

module "nodewright_operator" {
  source = "./modules/component"

  release_name  = "nodewright-operator"
  namespace     = "skyhook"
  chart         = "oci://ghcr.io/nvidia/nodewright/charts/nodewright"
  chart_version = "v0.17.1"
  values_file   = "${path.module}/bundle/008-nodewright-operator/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint
}

module "prometheus_operator_crds" {
  source = "./modules/component"

  release_name  = "prometheus-operator-crds"
  namespace     = "monitoring"
  chart         = "prometheus-operator-crds"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "28.0.1"
  values_file   = "${path.module}/bundle/009-prometheus-operator-crds/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint
}

module "kube_prometheus_stack" {
  source = "./modules/component"

  release_name  = "kube-prometheus-stack"
  namespace     = "monitoring"
  chart         = "kube-prometheus-stack"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "84.4.0"
  values_file   = "${path.module}/bundle/010-kube-prometheus-stack/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.prometheus_operator_crds]
}

module "gpu_operator" {
  source = "./modules/component"

  release_name  = "gpu-operator"
  namespace     = "gpu-operator"
  chart         = "gpu-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v26.7.0"
  values_file   = "${path.module}/bundle/011-gpu-operator/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.cert_manager, module.kube_prometheus_stack, module.nfd]
}

module "k8s_ephemeral_storage_metrics" {
  source = "./modules/component"

  release_name  = "k8s-ephemeral-storage-metrics"
  namespace     = "monitoring"
  chart         = "k8s-ephemeral-storage-metrics"
  repository    = "https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart"
  chart_version = "1.19.2"
  values_file   = "${path.module}/bundle/012-k8s-ephemeral-storage-metrics/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.kube_prometheus_stack, module.prometheus_operator_crds]
}

module "kai_scheduler" {
  source = "./modules/component"

  release_name  = "kai-scheduler"
  namespace     = "kai-scheduler"
  chart         = "oci://ghcr.io/kai-scheduler/kai-scheduler/kai-scheduler"
  chart_version = "v0.16.9"
  values_file   = "${path.module}/bundle/013-kai-scheduler/values.yaml"
  wait          = false # reconciles asynchronously; see ASYNC_COMPONENTS

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.gpu_operator]
}

module "nvidia_dra_driver_gpu" {
  source = "./modules/component"

  release_name  = "nvidia-dra-driver-gpu"
  namespace     = "nvidia-dra-driver"
  chart         = "oci://registry.k8s.io/dra-driver-nvidia/charts/dra-driver-nvidia-gpu"
  chart_version = "0.5.0"
  values_file   = "${path.module}/bundle/014-nvidia-dra-driver-gpu/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.gpu_operator]
}

module "nvsentinel" {
  source = "./modules/component"

  release_name  = "nvsentinel"
  namespace     = "nvsentinel"
  chart         = "oci://ghcr.io/nvidia/nvsentinel"
  chart_version = "v1.20.0"
  values_file   = "${path.module}/bundle/015-nvsentinel/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.cert_manager, module.gpu_operator, module.prometheus_operator_crds]
}

module "prometheus_adapter" {
  source = "./modules/component"

  release_name  = "prometheus-adapter"
  namespace     = "monitoring"
  chart         = "prometheus-adapter"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "5.3.0"
  values_file   = "${path.module}/bundle/016-prometheus-adapter/values.yaml"

  cluster_endpoint = kind_cluster.dc.endpoint

  depends_on = [module.kube_prometheus_stack]
}
