# The cluster, and the AICR bundle that fills it.
#
# Everything under bundle/ is generated by `aicr bundle --deployer terraform`.
# This file and versions.tf are the only hand-written Terraform in the example,
# and they exist to do the one thing AICR will not: put the cluster in the graph.

resource "kind_cluster" "dc" {
  name           = "${var.cluster_name}-${var.generation}"
  node_image     = var.node_image
  wait_for_ready = true
}

module "stack" {
  source = "./bundle"

  # Nothing in the bundle connects with this. It is the containment trigger:
  # replace the cluster and every release in it is replaced too, instead of
  # being adopted by a cluster that has never seen it.
  cluster_endpoint = kind_cluster.dc.endpoint
}
