# Generated by x-tfgen from an AICR recipe. Do not edit by hand.
terraform {
  required_providers {
    kind = {
      source  = "tehcyx/kind"
      version = "0.11.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }

  backend "local" {
    path = "terraform.tfstate"
  }
}

provider "kind" {}

# Bound to the cluster's computed outputs, so the provider configuration is
# unknown until the cluster is applied. That is the whole point of the
# experiment: every release below is unplannable on the first walk.
provider "helm" {
  kubernetes = {
    host                   = kind_cluster.dc.endpoint
    client_certificate     = kind_cluster.dc.client_certificate
    client_key             = kind_cluster.dc.client_key
    cluster_ca_certificate = kind_cluster.dc.cluster_ca_certificate
  }
}
