# Generated by AICR dev — do not edit.
#
# One module call per component. depends_on carries the recipe's graph exactly:
# a component waits for its declared dependencies and nothing else, so
# independent components apply concurrently. A component's own pre / post /
# readiness folders chain inside the module, which is why depending on the
# module means the component is done.

# 001-aws-ebs-csi-driver — aws-ebs-csi-driver 2.59.0
module "aws_ebs_csi_driver" {
  source = "./modules/component"

  release_name     = "aws-ebs-csi-driver"
  namespace        = "kube-system"
  create_namespace = true

  chart         = "aws-ebs-csi-driver"
  repository    = "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
  chart_version = "2.59.0"

  values_files = [
    "${path.module}/001-aws-ebs-csi-driver/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 002-aws-efa — aws-efa-k8s-device-plugin v0.5.29
module "aws_efa" {
  source = "./modules/component"

  release_name     = "aws-efa"
  namespace        = "kube-system"
  create_namespace = true

  chart         = "aws-efa-k8s-device-plugin"
  repository    = "https://aws.github.io/eks-charts"
  chart_version = "v0.5.29"

  values_files = [
    "${path.module}/002-aws-efa/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 003-cert-manager — cert-manager v1.20.2
module "cert_manager" {
  source = "./modules/component"

  release_name     = "cert-manager"
  namespace        = "cert-manager"
  create_namespace = true

  chart         = "cert-manager"
  repository    = "https://charts.jetstack.io"
  chart_version = "v1.20.2"

  values_files = [
    "${path.module}/003-cert-manager/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 004-nfd — node-feature-discovery 0.19.0
module "nfd" {
  source = "./modules/component"

  release_name     = "nfd"
  namespace        = "node-feature-discovery"
  create_namespace = true

  chart         = "node-feature-discovery"
  repository    = "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chart_version = "0.19.0"

  values_files = [
    "${path.module}/004-nfd/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 005-nodewright-operator — nodewright v0.19.0
module "nodewright_operator" {
  source = "./modules/component"

  release_name     = "nodewright-operator"
  namespace        = "skyhook"
  create_namespace = true

  chart         = "nodewright"
  repository    = "oci://ghcr.io/nvidia/nodewright/charts"
  chart_version = "v0.19.0"

  values_files = [
    "${path.module}/005-nodewright-operator/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 006-nodewright-customizations — chart bundled in this directory
module "nodewright_customizations" {
  source = "./modules/component"

  release_name     = "nodewright-customizations"
  namespace        = "skyhook"
  create_namespace = true

  chart = "${path.module}/006-nodewright-customizations"

  values_files = [
    "${path.module}/006-nodewright-customizations/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.nodewright_operator,
  ]
}

# 007-prometheus-operator-crds — prometheus-operator-crds 28.0.1
module "prometheus_operator_crds" {
  source = "./modules/component"

  release_name     = "prometheus-operator-crds"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "prometheus-operator-crds"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "28.0.1"

  values_files = [
    "${path.module}/007-prometheus-operator-crds/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 008-kube-prometheus-stack — kube-prometheus-stack 84.4.0
module "kube_prometheus_stack" {
  source = "./modules/component"

  release_name     = "kube-prometheus-stack"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "kube-prometheus-stack"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "84.4.0"

  values_files = [
    "${path.module}/008-kube-prometheus-stack/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.prometheus_operator_crds,
  ]
}

# 009-gpu-operator — gpu-operator v26.7.0
module "gpu_operator" {
  source = "./modules/component"

  release_name     = "gpu-operator"
  namespace        = "gpu-operator"
  create_namespace = true

  chart         = "gpu-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v26.7.0"

  values_files = [
    "${path.module}/009-gpu-operator/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.cert_manager,
    module.kube_prometheus_stack,
    module.nfd,
    module.nodewright_customizations,
  ]
}

# 010-k8s-ephemeral-storage-metrics — k8s-ephemeral-storage-metrics 1.19.2
module "k8s_ephemeral_storage_metrics" {
  source = "./modules/component"

  release_name     = "k8s-ephemeral-storage-metrics"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "k8s-ephemeral-storage-metrics"
  repository    = "https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart"
  chart_version = "1.19.2"

  values_files = [
    "${path.module}/010-k8s-ephemeral-storage-metrics/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.kube_prometheus_stack,
    module.prometheus_operator_crds,
  ]
}

# 011-kai-scheduler — kai-scheduler v0.16.9
module "kai_scheduler" {
  source = "./modules/component"

  release_name     = "kai-scheduler"
  namespace        = "kai-scheduler"
  create_namespace = true

  chart         = "kai-scheduler"
  repository    = "oci://ghcr.io/kai-scheduler/kai-scheduler"
  chart_version = "v0.16.9"

  values_files = [
    "${path.module}/011-kai-scheduler/values.yaml",
  ]

  # Asynchronous: helm --wait times out on this component's custom-resource
  # readiness even though its pods start. Ordering still holds; readiness does not.
  atomic           = var.atomic
  wait             = false
  timeout          = 1200
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.gpu_operator,
  ]
}

# 012-kubeflow-trainer — kubeflow-trainer 2.2.0
# plus 013-kubeflow-trainer-post
module "kubeflow_trainer" {
  source = "./modules/component"

  release_name     = "kubeflow-trainer"
  namespace        = "kubeflow"
  create_namespace = true

  chart         = "kubeflow-trainer"
  repository    = "oci://ghcr.io/kubeflow/charts"
  chart_version = "2.2.0"

  values_files = [
    "${path.module}/012-kubeflow-trainer/values.yaml",
  ]

  post_chart = "${path.module}/013-kubeflow-trainer-post"

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.cert_manager,
    module.gpu_operator,
    module.kube_prometheus_stack,
  ]
}

# 014-nvcre — cluster-readiness-engine v0.2.0
module "nvcre" {
  source = "./modules/component"

  release_name     = "nvcre"
  namespace        = "nvcre"
  create_namespace = true

  chart         = "cluster-readiness-engine"
  repository    = "oci://ghcr.io/nvidia"
  chart_version = "v0.2.0"

  values_files = [
    "${path.module}/014-nvcre/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.kubeflow_trainer,
  ]
}

# 015-nvidia-dra-driver-gpu — dra-driver-nvidia-gpu 0.5.0
module "nvidia_dra_driver_gpu" {
  source = "./modules/component"

  release_name     = "nvidia-dra-driver-gpu"
  namespace        = "nvidia-dra-driver"
  create_namespace = true

  chart         = "dra-driver-nvidia-gpu"
  repository    = "oci://registry.k8s.io/dra-driver-nvidia/charts"
  chart_version = "0.5.0"

  values_files = [
    "${path.module}/015-nvidia-dra-driver-gpu/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.gpu_operator,
  ]
}

# 016-nvsentinel — nvsentinel v1.20.0
module "nvsentinel" {
  source = "./modules/component"

  release_name     = "nvsentinel"
  namespace        = "nvsentinel"
  create_namespace = true

  chart         = "nvsentinel"
  repository    = "oci://ghcr.io/nvidia"
  chart_version = "v1.20.0"

  values_files = [
    "${path.module}/016-nvsentinel/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.cert_manager,
    module.gpu_operator,
    module.prometheus_operator_crds,
  ]
}

# 017-prometheus-adapter — prometheus-adapter 5.3.0
module "prometheus_adapter" {
  source = "./modules/component"

  release_name     = "prometheus-adapter"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "prometheus-adapter"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "5.3.0"

  values_files = [
    "${path.module}/017-prometheus-adapter/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.kube_prometheus_stack,
  ]
}
