# Generated by AICR dev — do not edit.

output "criteria" {
  description = "The AICR criteria this bundle was resolved from."
  value       = "criteria(service=eks, accelerator=h100, intent=training, os=ubuntu, platform=kubeflow)"
}

output "components" {
  description = "Component -> namespace, for every component in the recipe."
  value = {
    "aws-ebs-csi-driver"            = "kube-system"
    "aws-efa"                       = "kube-system"
    "cert-manager"                  = "cert-manager"
    "nfd"                           = "node-feature-discovery"
    "nodewright-operator"           = "skyhook"
    "nodewright-customizations"     = "skyhook"
    "prometheus-operator-crds"      = "monitoring"
    "kube-prometheus-stack"         = "monitoring"
    "gpu-operator"                  = "gpu-operator"
    "k8s-ephemeral-storage-metrics" = "monitoring"
    "kai-scheduler"                 = "kai-scheduler"
    "kubeflow-trainer"              = "kubeflow"
    "nvcre"                         = "nvcre"
    "nvidia-dra-driver-gpu"         = "nvidia-dra-driver"
    "nvsentinel"                    = "nvsentinel"
    "prometheus-adapter"            = "monitoring"
  }
}

output "releases" {
  description = "Helm release -> namespace, auxiliary pre/post/readiness releases included."
  value = {
    "aws-ebs-csi-driver"            = "kube-system"
    "aws-efa"                       = "kube-system"
    "cert-manager"                  = "cert-manager"
    "nfd"                           = "node-feature-discovery"
    "nodewright-operator"           = "skyhook"
    "nodewright-customizations"     = "skyhook"
    "prometheus-operator-crds"      = "monitoring"
    "kube-prometheus-stack"         = "monitoring"
    "gpu-operator"                  = "gpu-operator"
    "k8s-ephemeral-storage-metrics" = "monitoring"
    "kai-scheduler"                 = "kai-scheduler"
    "kubeflow-trainer"              = "kubeflow"
    "kubeflow-trainer-post"         = "kubeflow"
    "nvcre"                         = "nvcre"
    "nvidia-dra-driver-gpu"         = "nvidia-dra-driver"
    "nvsentinel"                    = "nvsentinel"
    "prometheus-adapter"            = "monitoring"
  }
}

output "namespaces" {
  description = "Distinct namespaces the bundle installs into."
  value       = distinct(["kube-system", "kube-system", "cert-manager", "node-feature-discovery", "skyhook", "skyhook", "monitoring", "monitoring", "gpu-operator", "monitoring", "kai-scheduler", "kubeflow", "nvcre", "nvidia-dra-driver", "nvsentinel", "monitoring"])
}
