# Generated by AICR dev — do not edit.
#
# One module call per release. depends_on carries the recipe's dependency
# graph exactly: a component waits for its declared dependencies and nothing
# else, so independent components apply concurrently.

# 001-agentgateway-crds — agentgateway-crds v1.5.0
module "agentgateway_crds" {
  source = "./modules/component"

  release_name     = "agentgateway-crds"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway-crds"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/001-agentgateway-crds/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 002-agentgateway-crds-post — chart bundled in this directory
module "agentgateway_crds_post" {
  source = "./modules/component"

  release_name     = "agentgateway-crds-post"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart = "${path.module}/002-agentgateway-crds-post"

  values_files = [
    "${path.module}/002-agentgateway-crds-post/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.agentgateway_crds,
  ]
}

# 003-cert-manager — cert-manager v1.20.2
module "cert_manager" {
  source = "./modules/component"

  release_name     = "cert-manager"
  namespace        = "cert-manager"
  create_namespace = true

  chart         = "cert-manager"
  repository    = "https://charts.jetstack.io"
  chart_version = "v1.20.2"

  values_files = [
    "${path.module}/003-cert-manager/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 004-agentgateway — agentgateway v1.5.0
module "agentgateway" {
  source = "./modules/component"

  release_name     = "agentgateway"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart         = "agentgateway"
  repository    = "oci://cr.agentgateway.dev/charts"
  chart_version = "v1.5.0"

  values_files = [
    "${path.module}/004-agentgateway/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.agentgateway_crds_post,
    module.cert_manager,
  ]
}

# 005-agentgateway-post — chart bundled in this directory
module "agentgateway_post" {
  source = "./modules/component"

  release_name     = "agentgateway-post"
  namespace        = "agentgateway-system"
  create_namespace = true

  chart = "${path.module}/005-agentgateway-post"

  values_files = [
    "${path.module}/005-agentgateway-post/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.agentgateway,
  ]
}

# 006-nfd — node-feature-discovery 0.19.0
module "nfd" {
  source = "./modules/component"

  release_name     = "nfd"
  namespace        = "node-feature-discovery"
  create_namespace = true

  chart         = "node-feature-discovery"
  repository    = "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chart_version = "0.19.0"

  values_files = [
    "${path.module}/006-nfd/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 007-network-operator — network-operator 26.4.1
module "network_operator" {
  source = "./modules/component"

  release_name     = "network-operator"
  namespace        = "nvidia-network-operator"
  create_namespace = true

  chart         = "network-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "26.4.1"

  values_files = [
    "${path.module}/007-network-operator/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.cert_manager,
    module.nfd,
  ]
}

# 008-nodewright-operator — nodewright v0.17.1
module "nodewright_operator" {
  source = "./modules/component"

  release_name     = "nodewright-operator"
  namespace        = "skyhook"
  create_namespace = true

  chart         = "nodewright"
  repository    = "oci://ghcr.io/nvidia/nodewright/charts"
  chart_version = "v0.17.1"

  values_files = [
    "${path.module}/008-nodewright-operator/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 009-prometheus-operator-crds — prometheus-operator-crds 28.0.1
module "prometheus_operator_crds" {
  source = "./modules/component"

  release_name     = "prometheus-operator-crds"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "prometheus-operator-crds"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "28.0.1"

  values_files = [
    "${path.module}/009-prometheus-operator-crds/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint
}

# 010-kube-prometheus-stack — kube-prometheus-stack 84.4.0
module "kube_prometheus_stack" {
  source = "./modules/component"

  release_name     = "kube-prometheus-stack"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "kube-prometheus-stack"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "84.4.0"

  values_files = [
    "${path.module}/010-kube-prometheus-stack/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.prometheus_operator_crds,
  ]
}

# 011-gpu-operator — gpu-operator v26.7.0
module "gpu_operator" {
  source = "./modules/component"

  release_name     = "gpu-operator"
  namespace        = "gpu-operator"
  create_namespace = true

  chart         = "gpu-operator"
  repository    = "https://helm.ngc.nvidia.com/nvidia"
  chart_version = "v26.7.0"

  values_files = [
    "${path.module}/011-gpu-operator/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.cert_manager,
    module.kube_prometheus_stack,
    module.nfd,
  ]
}

# 012-k8s-ephemeral-storage-metrics — k8s-ephemeral-storage-metrics 1.19.2
module "k8s_ephemeral_storage_metrics" {
  source = "./modules/component"

  release_name     = "k8s-ephemeral-storage-metrics"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "k8s-ephemeral-storage-metrics"
  repository    = "https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart"
  chart_version = "1.19.2"

  values_files = [
    "${path.module}/012-k8s-ephemeral-storage-metrics/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.kube_prometheus_stack,
    module.prometheus_operator_crds,
  ]
}

# 013-kai-scheduler — kai-scheduler v0.16.9
module "kai_scheduler" {
  source = "./modules/component"

  release_name     = "kai-scheduler"
  namespace        = "kai-scheduler"
  create_namespace = true

  chart         = "kai-scheduler"
  repository    = "oci://ghcr.io/kai-scheduler/kai-scheduler"
  chart_version = "v0.16.9"

  values_files = [
    "${path.module}/013-kai-scheduler/values.yaml",
  ]

  # Asynchronous: helm --wait times out on this component's custom-resource
  # readiness even though its pods start. Ordering still holds; readiness does not.
  atomic           = var.atomic
  wait             = false
  timeout          = 1200
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.gpu_operator,
  ]
}

# 014-nvidia-dra-driver-gpu — dra-driver-nvidia-gpu 0.5.0
module "nvidia_dra_driver_gpu" {
  source = "./modules/component"

  release_name     = "nvidia-dra-driver-gpu"
  namespace        = "nvidia-dra-driver"
  create_namespace = true

  chart         = "dra-driver-nvidia-gpu"
  repository    = "oci://registry.k8s.io/dra-driver-nvidia/charts"
  chart_version = "0.5.0"

  values_files = [
    "${path.module}/014-nvidia-dra-driver-gpu/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.gpu_operator,
  ]
}

# 015-nvsentinel — nvsentinel v1.20.0
module "nvsentinel" {
  source = "./modules/component"

  release_name     = "nvsentinel"
  namespace        = "nvsentinel"
  create_namespace = true

  chart         = "nvsentinel"
  repository    = "oci://ghcr.io/nvidia"
  chart_version = "v1.20.0"

  values_files = [
    "${path.module}/015-nvsentinel/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.cert_manager,
    module.gpu_operator,
    module.prometheus_operator_crds,
  ]
}

# 016-prometheus-adapter — prometheus-adapter 5.3.0
module "prometheus_adapter" {
  source = "./modules/component"

  release_name     = "prometheus-adapter"
  namespace        = "monitoring"
  create_namespace = true

  chart         = "prometheus-adapter"
  repository    = "https://prometheus-community.github.io/helm-charts"
  chart_version = "5.3.0"

  values_files = [
    "${path.module}/016-prometheus-adapter/values.yaml",
  ]

  atomic           = var.atomic
  wait             = var.wait
  timeout          = var.timeout
  cluster_endpoint = var.cluster_endpoint

  depends_on = [
    module.kube_prometheus_stack,
  ]
}
