# Generated by AICR dev — do not edit.

output "criteria" {
  description = "The AICR criteria this bundle was resolved from."
  value       = "criteria(service=kind, accelerator=h100, intent=inference, os=, platform=)"
}

output "releases" {
  description = "Release name -> namespace, for every release in the bundle."
  value = {
    "agentgateway-crds"             = "agentgateway-system"
    "agentgateway-crds-post"        = "agentgateway-system"
    "cert-manager"                  = "cert-manager"
    "agentgateway"                  = "agentgateway-system"
    "agentgateway-post"             = "agentgateway-system"
    "nfd"                           = "node-feature-discovery"
    "network-operator"              = "nvidia-network-operator"
    "nodewright-operator"           = "skyhook"
    "prometheus-operator-crds"      = "monitoring"
    "kube-prometheus-stack"         = "monitoring"
    "gpu-operator"                  = "gpu-operator"
    "k8s-ephemeral-storage-metrics" = "monitoring"
    "kai-scheduler"                 = "kai-scheduler"
    "nvidia-dra-driver-gpu"         = "nvidia-dra-driver"
    "nvsentinel"                    = "nvsentinel"
    "prometheus-adapter"            = "monitoring"
  }
}

output "namespaces" {
  description = "Distinct namespaces the bundle installs into."
  value       = distinct(["agentgateway-system", "agentgateway-system", "cert-manager", "agentgateway-system", "agentgateway-system", "node-feature-discovery", "nvidia-network-operator", "skyhook", "monitoring", "monitoring", "gpu-operator", "monitoring", "kai-scheduler", "nvidia-dra-driver", "nvsentinel", "monitoring"])
}
