# Generated by AICR dev — do not edit.

variable "cluster_endpoint" {
  description = <<-EOT
    API endpoint of the containing cluster. Nothing reads it for connection —
    the provider comes from the caller. It exists so each release is contained
    by the cluster: replace the cluster and every release is replaced with it,
    rather than being adopted by a cluster that has never seen it.
  EOT
  type        = string
}

variable "wait" {
  description = <<-EOT
    Wait for each release's workloads to become ready before the resource is
    considered applied. This is what makes depends_on mean "the dependency is
    running", not merely "its manifests were submitted" — leave it on unless a
    component in this recipe is known to never converge (see README.md).
  EOT
  type        = bool
  default     = true
}

variable "timeout" {
  description = <<-EOT
    Per-release wait timeout, in seconds. Generous on purpose: several
    components in a datacenter recipe pull large images before any workload
    reports ready, and a short timeout turns a slow install into a confusing
    failure. A genuine hang is only delayed by this, not hidden.
  EOT
  type        = number
  default     = 900
}

variable "atomic" {
  description = "Roll a release back if it fails to install. Off by default: a failed release left in place is easier to diagnose."
  type        = bool
  default     = false
}
