# Generated by AICR dev — do not edit.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

# No provider block: this bundle is a CHILD MODULE. The calling configuration
# declares and configures the helm provider, and these module calls inherit it.
#
# That is what makes the cluster-in-the-same-configuration case work. The
# caller can point the provider straight at a cluster resource's attributes:
#
#   provider "helm" {
#     kubernetes = {
#       host                   = kind_cluster.dc.endpoint
#       cluster_ca_certificate = kind_cluster.dc.cluster_ca_certificate
#       client_certificate     = kind_cluster.dc.client_certificate
#       client_key             = kind_cluster.dc.client_key
#     }
#   }
#
#   module "stack" {
#     source = "./bundle"
#   }
#
# Those attributes are unknown until the cluster is created, so on the first
# pass every release here is unplannable. An engine with deferred actions
# converges that in two rounds; stock `terraform apply` needs the cluster first.
